// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feed_follow.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createFeedFollow = `-- name: CreateFeedFollow :one
WITH inserted AS (
    INSERT INTO feed_follows (id, user_id, feed_id)
    VALUES ($1, $2, $3)
    RETURNING feed_id
)
SELECT
    feed.id,
    feed.name,
    feed.url,
    users.name AS user_name
FROM inserted
JOIN feed ON feed.id = inserted.feed_id
JOIN users ON feed.user_id = users.id
`

type CreateFeedFollowParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
	FeedID uuid.UUID
}

type CreateFeedFollowRow struct {
	ID       uuid.UUID
	Name     string
	Url      string
	UserName string
}

func (q *Queries) CreateFeedFollow(ctx context.Context, arg CreateFeedFollowParams) (CreateFeedFollowRow, error) {
	row := q.db.QueryRowContext(ctx, createFeedFollow, arg.ID, arg.UserID, arg.FeedID)
	var i CreateFeedFollowRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.UserName,
	)
	return i, err
}

const getFollowsForUser = `-- name: GetFollowsForUser :many
SELECT
    feed.id,
    feed.name,
    feed.url,
    users.name AS user_name
FROM feed_follows
JOIN feed ON feed_follows.feed_id = feed.id
JOIN users ON feed.user_id = users.id
WHERE feed_follows.user_id = $1
`

type GetFollowsForUserRow struct {
	ID       uuid.UUID
	Name     string
	Url      string
	UserName string
}

func (q *Queries) GetFollowsForUser(ctx context.Context, userID uuid.UUID) ([]GetFollowsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getFollowsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFollowsForUserRow
	for rows.Next() {
		var i GetFollowsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unfollowFeed = `-- name: UnfollowFeed :exec
DELETE FROM feed_follows WHERE user_id = $1 AND feed_id = $2
`

type UnfollowFeedParams struct {
	UserID uuid.UUID
	FeedID uuid.UUID
}

func (q *Queries) UnfollowFeed(ctx context.Context, arg UnfollowFeedParams) error {
	_, err := q.db.ExecContext(ctx, unfollowFeed, arg.UserID, arg.FeedID)
	return err
}
